[package]
name = "queens"
version = "0.1.0"
edition = "2024"

[dependencies]
bit-board = "0.4.2"
bitvec = "1.0.1"
clap = { version = "4.5.40", features = ["derive"] }
itertools = "0.14.0"

[dev-dependencies]
criterion = "0.5.1"
rstest = "0.25.0"

[[bench]]
name = "my_benchmark"
harness = false
